base_url = "https://zola-after-dark.netlify.com"
compile_sass = true
title = "after-dark theme"
description = ""

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Vincent"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "My blog"
