name = "after-dark"
description = "A robust, elegant dark theme"
license = "MIT"
homepage = "https://github.com/getzola/after-dark"
min_version = "0.5.0"
demo = "https://zola-after-dark.netlify.com"

[extra]


[author]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"

[original]
author =  "comfusion"
homepage = "https://git.habd.as/comfusion/after-dark/"
repo = "https://git.habd.as/comfusion/after-dark/"
